### ISSUE TITLE
"marko" itself is no longer a dependency?

### ISSUE THREAD

**Issue by davidosomething** [marko-js/markoify#5]
saw it was removed for 2.2.0, should it be mentioned as a peer?

**Comment by patrick-steele-idem** [comment]
Sorry about that. I meant to publish that as a major upgrade. But, yes, it was intentional to remove `marko` as a dependency because the plugin works with multiple versions of `marko` and we don't want to pick a version. `peerDependencies` are problematic in older versions of `npm` so I don't want to add `marko` as a `peerDependency`. Instead, the app needs to make sure to install a version of `marko`. If more people complain I will back out the change, but for now, please install the appropriate version of `marko`.

Please let me know if you still see issues.
